// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7y9hwC4Kael97j-8EU4vEpV_iFRV6luw',
    appId: '1:126046489971:android:4c35bf6b77c824b14f0906',
    messagingSenderId: '126046489971',
    projectId: 'flutter-golf-club-b684e',
    storageBucket: 'flutter-golf-club-b684e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIMg_cybPHmahaBw7QfHtPUgkWc8bMQvA',
    appId: '1:126046489971:ios:790a2c95103145564f0906',
    messagingSenderId: '126046489971',
    projectId: 'flutter-golf-club-b684e',
    storageBucket: 'flutter-golf-club-b684e.firebasestorage.app',
    androidClientId: '126046489971-th27vkq3eflvcai0nb96m4h1ovecibkv.apps.googleusercontent.com',
    iosClientId: '126046489971-e20htdoppeidtfm4jht5et7qk4r1di1v.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

}